A bit of work later...
AvianGeneticist/TaleOfApoxys pull request #2
Opened 2022-08-24 10:26 UTC by DOD8495Gym

I finally managed to figure out how to edit files in GitHub. Now you have a choice: to allow players to defer level ups for whatever reason, or to toss all of my medium work out the window and not allow them to. I hope that I have removed the exploit that allows level up boosts to be gained by simply deferring levels, and I hope that this will allow players who wish to delay leveling up for whatever reason to be able to do so without getting too overpowered.

2022-08-24 17:04 UTC, AvianGeneticist requested changes
Seems fairly airtight; though I'd like for the Apoxys alt to be its own separate merge, rather than part of this pull request. Nix the image, and I'd be willing to put it into the mod proper.

2022-08-27 00:16 UTC, DOD8495Gym commented
Understood. Working on that.

2022-08-27 00:23 UTC, DOD8495Gym commented
Done. I admit, there's still optimizations that can be made, but the image is gone.

2022-08-27 11:42 UTC, DOD8495Gym commented
Actually, I've made an improvement to the changes I've already made. Closing pull request.

2022-08-27 11:42 UTC, closed without merging